apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: test-full-lifecycle-sept27 
  janus-idp.io/tekton: test-full-lifecycle-sept27
  backstage.io/kubernetes-id: test-full-lifecycle-sept27
  backstage.io/kubernetes-namespace: ai-rhdh-app-development 
  app.kubernetes.io/part-of: test-full-lifecycle-sept27
resources: 
- application-dev.yaml