apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: test-full-lifecycle-sept27-gitops-repository
spec:
  url: https://github.com/jdubrick-ai/test-full-lifecycle-sept27-gitops